#on: [push]
on:
  pull_request:
    types:
      - closed

jobs:
  hello_world_job:
    #if: github.event.pull_request.merged && contains( github.event.pull_request.labels.*.name, 'docs')
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: stable-website
    - run: |
        git fetch --no-tags --prune origin master
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git cherry-pick ${{ github.sha }}
        git push origin stable-website
